# Generated by Django 4.2.4 on 2023-10-02 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
